package main

import (
	"encoding/json"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("coach codesignal --baseline --check-project --project-language typescript: package-manager setup scoping (SA-280-045)", func() {
	When("a committed yarn.lock exists and the project's TypeScript compiler already resolves as installed and supported", func() {
		It("reports checks.package_manager fail/package_manager_version_unsupported for information only, contributing no gap and no resolve_package_manager action", func() {
			repo := newTempGitRepo()
			commitFile(repo, "package.json", `{"name":"example","version":"1.0.0","devDependencies":{"typescript":"7.0.2"}}`+"\n")
			commitFile(repo, "yarn.lock", "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n")
			writeInstalledTypescript(repo, "7.0.2")
			commitFile(repo, "tsconfig.json", `{"compilerOptions":{}}`+"\n")

			path := pathWithStubNode("v24.9.9")

			stdout, stderr, exitCode := runCoachCheckProjectEnv(repo, path, "--baseline", "--check-project", "--project-language", "typescript", "--format", "json")
			Expect(exitCode).To(Equal(0), "stderr: %s", stderr)

			var doc readinessResultDoc
			Expect(json.Unmarshal(stdout, &doc)).To(Succeed(), "stdout: %s", stdout)
			Expect(doc.Checks.Compiler.State).To(Equal("pass"), "the compiler must resolve for this fixture to isolate the SA-280-045 suppression rule, stdout=%s", stdout)
			Expect(doc.Checks.PackageManager.State).To(Equal("fail"), "the rejected Yarn adapter is still reported on checks.package_manager for information, stdout=%s", stdout)
			Expect(doc.Checks.PackageManager.Code).To(Equal("package_manager_version_unsupported"))
			Expect(doc.Checks.PackageManager.Kind).To(Equal("yarn"))
			Expect(gapCodes(doc)).NotTo(ContainElement("package_manager_version_unsupported"), "a package_manager_* code must not become a gap while the compiler already resolves (SA-280-045), stdout=%s", stdout)
			Expect(nextActionKinds(doc)).NotTo(ContainElement("resolve_package_manager"))
		})
	})

	When("a committed yarn.lock exists and no TypeScript compiler resolves, with no verifiable mise origin on PATH", func() {
		It("reports package_manager_version_unsupported as a gap with a resolve_package_manager action naming yarn, and withholds prepare_compiler since no other installation choice is verified", func() {
			repo := newTempGitRepo()
			commitFile(repo, "package.json", `{"name":"example","version":"1.0.0"}`+"\n")
			commitFile(repo, "yarn.lock", "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n")

			path := pathWithStubNode("v24.9.9")

			stdout, stderr, exitCode := runCoachCheckProjectEnv(repo, path, "--baseline", "--check-project", "--project-language", "typescript", "--format", "json")
			Expect(exitCode).To(Equal(0), "stderr: %s", stderr)

			var doc readinessResultDoc
			Expect(json.Unmarshal(stdout, &doc)).To(Succeed(), "stdout: %s", stdout)
			Expect(doc.Checks.Compiler.State).To(Equal("fail"))
			Expect(doc.Checks.Compiler.Code).To(Equal("typescript_compiler_missing"))
			Expect(doc.Checks.PackageManager.State).To(Equal("fail"))
			Expect(doc.Checks.PackageManager.Code).To(Equal("package_manager_version_unsupported"))
			Expect(gapCodes(doc)).To(ContainElements("typescript_compiler_missing", "package_manager_version_unsupported"), "got %+v stdout=%s", doc.Gaps, stdout)
			Expect(doc.NextActions).To(ContainElement(HaveField("PackageManagerKind", "yarn")), "the resolve_package_manager action must name which adapter was rejected, got %+v stdout=%s", doc.NextActions, stdout)
			Expect(nextActionKinds(doc)).To(ContainElement("resolve_package_manager"))
			Expect(nextActionKinds(doc)).NotTo(ContainElement("prepare_compiler"), "prepare_compiler must be withheld when the only installation choice (the Yarn adapter) is rejected and no mise origin is verified (SA-280-045), got %+v stdout=%s", doc.NextActions, stdout)
		})
	})

	When("a committed yarn.lock exists and no TypeScript compiler resolves, rendered in the default text format", func() {
		It("keeps the package_manager_kind discriminator on both the Gaps line and the resolve_package_manager next-action line", func() {
			repo := newTempGitRepo()
			commitFile(repo, "package.json", `{"name":"example","version":"1.0.0"}`+"\n")
			commitFile(repo, "yarn.lock", "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n")

			path := pathWithStubNode("v24.9.9")

			stdout, stderr, exitCode := runCoachCheckProjectEnv(repo, path, "--baseline", "--check-project", "--project-language", "typescript")
			Expect(exitCode).To(Equal(0), "stderr: %s", stderr)

			text := string(stdout)
			Expect(text).To(ContainSubstring("package_manager_version_unsupported package_manager_kind=yarn"), "the Gaps list must carry the same package_manager_kind discriminator as the JSON gaps[] entry (AC-12), got:\n%s", text)
			Expect(text).To(ContainSubstring("resolve_package_manager (executable=false) package_manager_kind=yarn"), "got:\n%s", text)
			Expect(text).To(ContainSubstring("\n  typescript_compiler_missing\n"), "a gap with no package_manager_kind must still render as a bare code, got:\n%s", text)
		})
	})
})
